### PR TITLE
[TASK] Verify PHP 8.2 support

### PR DESCRIPTION
**Pull request by mteu**

### CODE REVIEW

**Comment by mteu** [comment]
Workflows weren't allowed to be run. Verifying on my personal account.

**Comment by eliashaeussler** [comment]
Hi @mteu, I'm currently phasing out this library and will merge it into the update-check library, see eliashaeussler/composer-update-check#89. The codebase within that PR should already be PHP 8.2 compatible.

**Comment by mteu** [comment]
I see. So it wouldn't make too much sense to create a Composer plugin based off `eliashaeussler/composer-update-reporter` I presume?

**Comment by eliashaeussler** [comment]
> I see. So it wouldn't make too much sense to create a Composer plugin based off `eliashaeussler/composer-update-reporter` I presume?

Yes. Better wait for the next release of `eliashaeussler/composer-update-check` which will include the `eliashaeussler/composer-update-reporter` library. The `eliashaeussler/composer-update-reporter` plugin will be abandoned soon.

**Pull request closed without merging**
